### ISSUE TITLE
Cannot read save files containing Grand Charm

### ISSUE THREAD

**Issue by FavorekW** [zeddicus-pl/d2rHolyGrail#10]
After copying Grand Charm  to a character, there is an error on this character

**Comment by zeddicus-pl** [comment]
Is it the new GC with Sunder? did you download that save with Sunders maybe?
If so, that is not yet supported and shouldn't be an issue in single player yet

**Comment by FavorekW** [comment]
Yes it is. I downloaded the GC with Sunder from Nadin and copied it to my main character on single player.

**Comment by zeddicus-pl** [comment]
Alright then, closing this as non-bug because simply you are cheating ;) just joking, but I'll close it for now anyways, because Sunder support will come in the next version, and these charms are not yet officially in single player.
