### ISSUE TITLE
Mosaic breaks save parsing

### ISSUE THREAD

**Issue by RyeToastyO** [zeddicus-pl/d2rHolyGrail#15]
Haven't tested other 2.6 runewords, but Mosaic definitely does.

**Comment by wjakiela** [comment]
Need to update github.com/dschu012 to v2.0.36

**Comment by maxoo66** [comment]
I have the same issue how we could do this update?

**Comment by zeddicus-pl** [comment]
Hi guys, sorry it takes that long. I had a really busy period, no time to do anything hobby related... thanks for reminding me of this, I'll do my best to get these fixes out today or tomorrow

**Comment by maxoo66** [comment]
ok thx a lot I ll wait the update so !

**Comment by zeddicus-pl** [comment]
I actually am having problems compiling the app on my new laptop :-/ I got
changes merged, plus some missing translations, but it'll take me a moment
to figure out how to make the electron native modules compile.

wt., 25 kwi 2023 o 20:03 maxoo66 ***@***.***> napisał(a):

**Comment by zeddicus-pl** [comment]
the app is now updated, I don't have a save to test it so please reopen the Issue if the problem still exists
