### ISSUE TITLE
Error with file type

### ISSUE THREAD

**Issue by grassfedpotato** [zeddicus-pl/d2rHolyGrail#2]
I am using some mods for single player. It was working when I pointed it to the correct directory. Now it is not and when I expand, 'Save Files Summary' it says, "Error" under items read. Please help.

**Comment by zeddicus-pl** [comment]
Hi, not sure if you are the same person who I talked to on Discord, but just for the record:
If you use mods that modify save files, there's a good chance these will break the app - the same as these saves would break the *game* itself if loaded without a mod.
In case of that person on Discord he was using "runestack" - an his saves were modified. The game itself also didn't read these saves without a mod enabled.

In case if that is something else, please msg me and we will figure out, but without any more details I will assume this is a mod that modifies save files - therefore, no fix is possible.
