### ISSUE TITLE
The 'ding' sounds plays at the wrong time

### ISSUE THREAD

**Issue by Headbomb** [zeddicus-pl/d2rHolyGrail#3]
When you have an unidentified unique item in your inventory, and also unidentified magical/rare items, the 'Ding' sound plays when identifying the magical/rares

I haven't noticed if the counter also updates at that time, but I believe the sound should only play when identifying the unique item, not the magical/rare items.

Love this program btw! Grailing has never been more fun!

**Comment by zeddicus-pl** [comment]
That's not a bug - the program plays a sound when it finds a new item in the saves. And it just happens that when you identify, leave the game, or each 5 minutes - the game saves the save file.
No way to change that.
