### ISSUE TITLE
Items in shared stash are not counted anymore

### ISSUE THREAD

**Issue by Ivovanhalen** [zeddicus-pl/d2rHolyGrail#7]
After the update, my number of items went down. I had some items in the shared stash. If I move the items from the shared stash to the character stash they get counted again

**Comment by Mrn1ceguy92** [comment]
Can second this issue, number of items went down then nearly doubled. And randomly when I login to other mules it's "dinging" and counting items up.

**Comment by oleggozhyi** [comment]
same

**Comment by Kad-Man** [comment]
Not only that it randomly dings for no reason also with no new items ive seen this happen to streamers also.

**Comment by zeddicus-pl** [comment]
Hi guys, thanks for reporting this. I'm not sure if the reason is patch 2.5 or the changes to d2s library that were made recently. I didn't have a moment to work on fixing this yet, but I will look into this as soon as I can.

**Comment by Ivovanhalen** [comment]
No rush. Love this project, makes the grail so much more fun. Thanks!

**Comment by Mrn1ceguy92** [comment]
> Hi guys, thanks for reporting this. I'm not sure if the reason is patch 2.5 or the changes to d2s library that were made recently. I didn't have a moment to work on fixing this yet, but I will look into this as soon as I can.

Thank you very much. We love this project- makes grailing that much more enjoyable!

**Comment by cwn-dev** [comment]
Mine is showing an error on SharedStashSoftCoreV2 under Save files summary

![image](https://user-images.githubusercontent.com/74492500/192116211-4b1602bb-8c16-4228-95a0-45404d09634e.png)

**Comment by Mrn1ceguy92** [comment]
> Mine is showing an error on SharedStashSoftCoreV2 under Save files summary
> 
> ![image](https://user-images.githubusercontent.com/74492500/192116211-4b1602bb-8c16-4228-95a0-45404d09634e.png)
> 
> May be related?
> 
> It seems to be reading my statistics properly initially, but when I moved an item from character to shared stash, the app loses track of it.

can confirm this as well. in-case it's related.

**Comment by zeddicus-pl** [comment]
This is fixed now. Thanks for your reports.

**Comment by eprediger** [comment]
This issue showed up after updating from 2.2.2 to 2.3.1 on LOD with Plugy mod

![imagen](https://user-images.githubusercontent.com/15719194/217845960-94e39cb9-5e0a-4e4b-9c0d-e227e659f941.png)
