### ISSUE TITLE
Cannot read save files containing personalized items

### ISSUE THREAD

**Issue by FluxNorton** [zeddicus-pl/d2rHolyGrail#8]
Hi
After the latest update, I still had 1 save file in error. After some testing, I found that it was caused by personalized items. 
By moving the items between chars and shared stash I could reproduce the error.
Right now all 3 of my personalized items are on a dedicated mule, and I only get the save error on this mule.
This is the workaround for me, as I luckily have duplicates of the 3 items. But hopefully you will have time to fix it at some point :)

Thank you so much for this software - somehow the dong just adds another level of excitement to the grail grinding!

**Comment by zeddicus-pl** [comment]
Fixed! Thanks for reporting
