### ISSUE TITLE
Random Dings on white items again.

### ISSUE THREAD

**Issue by Kad-Man** [zeddicus-pl/d2rHolyGrail#9]
After latest update getting random dings again off random items and not sure whats triggering it once it was a shadow bow another it was a town portal scroll.

**Comment by FluxNorton** [comment]
A comment to this: was watching MrLlamaSC's stream, and he was getting random dings while gambling rings.

**Comment by zeddicus-pl** [comment]
I released last fix for patch 2.5 yesterday night, not sure if you have this fix. Xan you please make sure to download the latedt version and try again please?

**Comment by FluxNorton** [comment]
The MrLlama stream was definitely before the latest fix. Let's see if it helped!
thanks again :)

**Comment by Kad-Man** [comment]
> I released last fix for patch 2.5 yesterday night, not sure if you have this fix. Xan you please make sure to download the latedt version and try again please?

I do have the latest and it was happening in chaos sanctuary the only thing I can think of that's causing it is having an unid item I don't have in grail yet in my inventory.

**Comment by zeddicus-pl** [comment]
I think this is fixed already, please ping me if you get this again in version 2.2.5
